import 'dart:convert';
import 'dart:io';

void main() async {
  final assetsDir = Directory('showcase_starsystem/assets');
  if (!assetsDir.existsSync()) {
    print('Error: showcase_starsystem/assets directory not found.');
    return;
  }

  final files = assetsDir.listSync().whereType<File>().where((file) {
    return file.path.endsWith('.png');
  });

  final buffer = StringBuffer();
  buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
  buffer.writeln('// This file is generated by tools/embed_starsystem_assets.dart');
  buffer.writeln();
  buffer.writeln('class EmbeddedAssets {');
  buffer.writeln("  static const Map<String, String> assets = {");

  for (final file in files) {
    final fileName = file.path.split(Platform.pathSeparator).last;
    final bytes = file.readAsBytesSync();
    final base64String = base64Encode(bytes);
    buffer.writeln("    '${fileName}': '${base64String}',");
  }

  buffer.writeln('  };');
  buffer.writeln('}');

  final outFile = File('showcase_starsystem/lib/embedded_assets.dart');
  await outFile.writeAsString(buffer.toString());
  print('Generated ${outFile.path}');
}
